### ISSUE TITLE
Add additional Voddi Etikett to ESN Shaker

### ISSUE THREAD

**Issue by MWilheEx** [crnnr/crnnr#1]
Currently the whole Voddi shaker is marked with various labels signifying his possession
However, the lid is detachable and is missing the appropriate label, so it can't be clearly assigned.

Please add another label to the lid of the Voddi shaker.

**Comment by crnnr** [comment]
This issue still has labelingproblems

**Comment by crnnr** [comment]
Added missing label in current shaker version release
